<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Authors>Grey-Wind</Authors>
    <Company>QingYi-Studio</Company>
    <Title>Encrypt</Title>
    <Description>DES/3DES/AES Encrypt</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QingYi.Core" Version="1.1.0">
      <Aliases></Aliases>
    </PackageReference>
  </ItemGroup>

</Project>
