<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <NuGetAuditLevel>high</NuGetAuditLevel>
    <NuGetAudit>True</NuGetAudit>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Version>0.1.0</Version>
    <Title>Rino Bool CLI</Title>
    <Authors>Grey-Wind</Authors>
    <Company>Qing Yi Studio</Company>
    <Product>Rino Bool CLI</Product>
    <Copyright>Closed source, no commercial use</Copyright>
    <PackageReleaseNotes>Base info</PackageReleaseNotes>
    <AssemblyName>rino</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SharedBaseLib\Rino.NewProject\Rino.NewProject.csproj" />
    <ProjectReference Include="..\..\SharedBaseLib\Rino.Versions\Rino.Versions.csproj" />
    <ProjectReference Include="..\Rino.CLI.Help\Rino.CLI.Help.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
